### ISSUE TITLE
Doesn't scroll

### ISSUE THREAD

**Issue by m-montoya** [kharrison/CodeExamples#12]
Following this it doesn't scroll for me like the prior used to.

**Comment by kharrison** [comment]
Can you provide a bit more information of what you're doing?

- Which project are you referring to? I'm assuming ScrollGuide-IB?
- How are you building and running? Which version of Xcode, iOS, simulator or device?
- If you take my sample code and build it with the latest version of Xcode 11 and run it on iOS 13 simulator or device and increase the dynamic type size does it scroll?

**Comment by kharrison** [comment]
OK, so the problem is not with my sample code but something you are trying to do in your own code?

How are you creating your constraints? Can you post your code somewhere?

Typically to handle resizing of the scroll view to allow for the keyboard you would adjust the contentInset (see [Unexpected keyboards](https://useyourloaf.com/blog/split-views-and-unexpected-keyboards/) for an example).

**Comment by m-montoya** [comment]
Prior to the new changes that came with 11, the old example you had worked very well with the being able to define a height for the scroll view. After the update and using the new example code given, defining a height for the scroll view as I was doing in the old example, things stopped working as they had. I already have some similar code to the link you posted for other areas app that were created prior to 11. Addition of a scroll view to a new area results in it not working.

The constraints are identical to the example. I then added a new height constraint to the scroll view.
`@IBOutlet weak var scrollViewHeightConstraint: NSLayoutConstraint!`

Attempts to adjust this in the notification for keyboardWillShow or keyboardWillHide like so
`scrollViewHeightConstraint.constant = 900`

The content would not scroll. If you haven't, you may try the new example code with a keyboard and the need to scroll up to view for example a textfield?

**Comment by kharrison** [comment]
I'm not seeing any problem when adjusting the scroll view contentInset which is how I would usually handle a keyboard.

How are you creating the height constraint? The scroll view in my example has its frame fully constrained to the root view, so adding an extra height constraint would not have any effect. Would be easier to help if you would post your code somewhere.

**Comment by m-montoya** [comment]
Sorry for the delay. Still can't get it to scroll. Unfortunately can't post code as there isn't any. All IB.  So the scenario is like so

- scrollview
- container view
- 3 views in it. each view has a defined height (300, 400, 200)

The constrains are identical to yours yet it won't scroll even though the content now stretches beyond the bottom of the phone. Did try removing the bottom constrain for the scrollview and setting a height for the scrollview but that didn't matter either.

**Comment by kharrison** [comment]
Post the entire Xcode project to a GitHub repo and drop the link here or email it to me. Without seeing how you are setting up the constraints it's hard to help more.

**Comment by m-montoya** [comment]
Here is the link to the repository [https://github.tamu.edu/m-montoya/scrolltest](https://github.tamu.edu/m-montoya/scrolltest) Thx

**Comment by clumsyhamster** [comment]
Oops. Sorry about that. Let's use the open 1. Try this [https://github.com/clumsyhamster/scrolltest](https://github.com/clumsyhamster/scrolltest) Thx

**Comment by kharrison** [comment]
You have a constraint from the bottom of the purple view to the bottom of the container view.
You are missing a constraint from the bottom of the green view to the bottom of the container view.

If I remove the purple constraint and add the missing green view constraint it scrolls.

One tip, try using the view debugger and examine the height of the container view.

**Comment by clumsyhamster** [comment]
Thx for the quit update on the fix for fixed height views. I found that for dynamic content where the bottom containers height is not known and if you try to just set the bottom constraint to the container or no constraint at all, it'll complain about the scrollview needing a defined y position or height. Any ideas?

**Comment by kharrison** [comment]
What do you mean when you say that the bottom containers height is not known?
- will it have an intrinsic content size at runtime? If so you can use a placeholder constraint in IB to remove the warning
- if the view has no intrinsic size you have to decide how big it will be. Maybe it will be some multiple of one of the other views or you might be sizing it to fit its content. See [Self sizing child views](https://useyourloaf.com/blog/self-sizing-child-views/) for another approach

Either way the height of the content container view needs to be set based on the content and it needs to be fully constrained the scroll view content layout guide.

**Comment by m-montoya** [comment]
Nevermind about this. Everything will generally have a defined height. I just need to figure out what that height will be and then define it. Appreciate all your help with this and thanks for your patience.
