### ISSUE TITLE
local-notifications-with-ios-10

### ISSUE THREAD

**Issue by Jacky-LinPeng** [kharrison/CodeExamples#13]
As we know, notify count limit 64
The new framwork in ios 10, how to repeat 5s,

source:
 https://useyourloaf.com/blog/local-notifications-with-ios-10/

**Comment by kharrison** [comment]
There's really no reliable way to get around the limitations. The only advice I can offer is to file a feedback report to Apple describing the use case you want. I wouldn't hold my breath for a response but you never know...
